In [35]:
import sys
sys.path.insert(0, '../scripts')
sys.path.insert(0, '../data/database')
from sqlalchemy import create_engine
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [36]:
engine =  create_engine('sqlite:///../data/database/happycows.db')
with engine.connect() as con:
    weather = pd.read_sql_table('weather', con)

In [37]:
weather.head()

,index,STATION,NAME,LATITUDE,LONGITUDE,ELEVATION,DATE,PRCP,TMIN,TMAX
0,0,USC00361354,"CHAMBERSBURG, PA US",39.9353,-77.6394,195.1,2014-01-01,0.00,20.0,36.0
1,1,USC00361354,"CHAMBERSBURG, PA US",39.9353,-77.6394,195.1,2014-01-02,0.16,21.0,38.0
2,2,USC00361354,"CHAMBERSBURG, PA US",39.9353,-77.6394,195.1,2014-01-03,0.00,8.0,38.0
3,3,USC00361354,"CHAMBERSBURG, PA US",39.9353,-77.6394,195.1,2014-01-04,0.00,6.0,28.0
4,4,USC00361354,"CHAMBERSBURG, PA US",39.9353,-77.6394,195.1,2014-01-05,0.35,11.0,33.0

In [38]:
def transform_tmax(data):
    """fill values for TMAX"""
    data[['TMAX']] =  data.groupby('DATE')[['TMAX']].transform(lambda x: x.fillna(x.mean()))
    return data

def transform_tmin(data):
    """fill values for TMIN"""
    data[['TMIN']] =  data.groupby('DATE')[['TMIN']].transform(lambda x: x.fillna(x.mean()))
    return data

def transform_precipitation(data):
    """fill values for PRCP"""
    data[['PRCP']] =  data.groupby('DATE')[['PRCP']].transform(lambda x: x.fillna(x.mean()))
    return data

def transform_date(data):
    """ Ensure DATE is a datetime """
    data['DATE'] = pd.to_datetime(weather['DATE'])
    data = data.groupby('DATE').mean().reset_index()
    return data.set_index(['DATE'])

def transform_features(data):
    data = transform_tmax(data)
    data = transform_tmin(data)
    data = transform_precipitation(data)
    data = transform_date(data)
    return data

def drop_features(data):
    """ Drop non-essential weather features. """
    data = data.reset_index()
    return data[['DATE', 'PRCP', 'TMIN', 'TMAX']].set_index('DATE')

def identify_heatwave(data):
    """Identify a day as hot if TMAX > 90.  Identify as heatwave if three consecutive hot days"""
    data['IS_HOT'] = data['TMAX'].apply(lambda x: x > 90)
    data['IS_HEATWAVE'] = data['IS_HOT'].rolling(3).sum() == 3
    return weather

def identify_coldwave(data):
    """Identify a day as cold if TMIN < 10.  Identify as coldwave if three consecutive cold days"""
    data['IS_COLD'] = data['TMIN'].apply(lambda x: x < 10)
    data['IS_COLDWAVE'] = data['IS_COLD'].rolling(3).sum() == 3
    return weather

def make_columns_lower(data):
    """Make all column headers lowercase"""
    data = data.reset_index()
    data.columns = [x.lower() for x in data.columns]
    return data

In [39]:
weather = transform_features(weather)
weather = drop_features(weather)
weather = identify_heatwave(weather)
weather = identify_coldwave(weather)
weather = make_columns_lower(weather)
weather.head(40)

         date      prcp  tmin  tmax  is_hot  is_heatwave  is_cold  is_coldwave
0  2014-01-01  0.000000  20.0  33.5   False        False    False        False
1  2014-01-02  0.053333  22.5  38.0   False        False    False        False
2  2014-01-03  0.130000   6.0  33.0   False        False     True        False
3  2014-01-04  0.000000   3.5  21.5   False        False     True        False
4  2014-01-05  0.116667  11.5  33.0   False        False    False        False
5  2014-01-06  0.296667  14.0  42.0   False        False    False        False
6  2014-01-07  0.000000  -5.5  23.0   False        False     True        False
7  2014-01-08  0.000000  -0.5  14.5   False        False     True        False
8  2014-01-09  0.000000  13.0  29.0   False        False    False        False
9  2014-01-10  0.063333  24.5  33.5   False        False    False        False
10 2014-01-11  0.206667  30.5  50.0   False        False    False        False
11 2014-01-12  0.200000  32.5  51.5   False        False    False        False
12 2014-01-13  0.000000  26.0  47.5   False        False    False        False
13 2014-01-14  0.146667  27.0  48.5   False        False    False        False
14 2014-01-15  0.063333  27.0  41.5   False        False    False        False
15 2014-01-16  0.000000  24.5  39.0   False        False    False        False
16 2014-01-17  0.000000  22.5  37.0   False        False    False        False
17 2014-01-18  0.076667  16.5  36.0   False        False    False        False
18 2014-01-19  0.003333  13.5  29.0   False        False    False        False
19 2014-01-20  0.000000  24.5  40.0   False        False    False        False
20 2014-01-21  0.143333  16.0  38.0   False        False    False        False
21 2014-01-22  0.120000  -1.5  17.0   False        False     True        False
22 2014-01-23  0.000000  -1.0  15.5   False        False     True        False
23 2014-01-24  0.000000   0.5  16.5   False        False     True         True
24 2014-01-25  0.000000   6.0  23.5   False        False     True         True
25 2014-01-26  0.003333   5.5  25.5   False        False     True         True
26 2014-01-27  0.000000  11.5  30.0   False        False    False        False
27 2014-01-28  0.000000   2.0  27.0   False        False     True        False
28 2014-01-29  0.000000   2.0  13.0   False        False     True        False
29 2014-01-30  0.000000   2.5  22.0   False        False     True         True
30 2014-01-31  0.000000  11.5  33.0   False        False    False        False
31 2014-02-01  0.000000  23.5  40.0   False        False    False        False
32 2014-02-02  0.000000  30.0  47.0   False        False    False        False
33 2014-02-03  0.873333  30.5  45.0   False        False    False        False
34 2014-02-04  0.080000  15.5  31.0   False        False    False        False
35 2014-02-05  0.896667  22.0  33.0   False        False    False        False
36 2014-02-06  0.000000  18.0  31.5   False        False    False        False
37 2014-02-07  0.000000  18.5  29.5   False        False    False        False
38 2014-02-08  0.000000  15.0  28.0   False        False    False        False
39 2014-02-09  0.043333  13.5  26.0   False        False    False        False